// chambre
export const GET_CHAMBRES = 'GET_CHAMBRES'
export const GET_CHAMBRE = 'GET_CHAMBRE'
export const EDIT_CHAMBRE = 'EDIT_CHAMBRE'
export const ADD_CHAMBRE = 'ADD_CHAMBRE'
export const DELETE_CHAMBRE = 'DELETE_CHAMBRE'

// categorie
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIE = 'GET_CATEGORIE'
export const EDIT_CATEGORIE = 'EDIT_CATEGORIE'
export const ADD_CATEGORIE = 'ADD_CATEGORIE'
export const DELETE_CATEGORIE = 'DELETE_CATEGORIE'


// Product
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT = 'GET_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

// Reservation
export const GET_RESERVATIONS = 'GET_RESERVATIONS'
export const GET_RESERVATION = 'GET_RESERVATION'
export const EDIT_RESERVATION = 'EDIT_RESERVATION'
export const ADD_RESERVATION = 'ADD_RESERVATION'
export const DELETE_RESERVATION = 'DELETE_RESERVATION'
// TYPE MESSAGE
export const GET_TYPE_MESSAGES = 'GET_TYPE_MESSAGES'

// SALLES
export const GET_SALLES = 'GET_SALLES'

// Bureaux
export const GET_BUREAUX = 'GET_BUREAUX'
//Parcours
export const GET_PARCOURS = 'GET_PARCOURS'
export const GET_PARCOUR = 'GET_PARCOUR'
export const EDIT_PARCOUR = 'EDIT_PARCOUR'
export const ADD_PARCOUR = 'ADD_PARCOUR'
export const DELETE_PARCOUR = 'DELETE_PARCOUR'

//COMPAGNIES
export const GET_COMPAGNIES = 'GET_COMPAGNIES'
export const GET_COMPAGNIE = 'GET_COMPAGNIE'
export const EDIT_COMPAGNIE = 'EDIT_COMPAGNIE'
export const ADD_COMPAGNIE = 'ADD_COMPAGNIE'
export const DELETE_COMPAGNIE = 'DELETE_COMPAGNIE' 
//Type Decisions
export const GET_TYPEDECISIONS = 'GET_TYPEDECISIONS'
export const GET_TYPEDECISION = 'GET_TYPEDECISION'
export const EDIT_TYPEDECISION = 'EDIT_TYPEDECISION'
export const ADD_TYPEDECISION = 'ADD_TYPEDECISION'
export const DELETE_TYPEDECISION = 'DELETE_TYPEDECISION'
//Personnel 
export const GET_PERSONNELS = 'GET_PERSONNELS'
export const GET_PERSONNEL = 'GET_PERSONNEL'
export const EDIT_PERSONNEL = 'EDIT_PERSONNEL'
export const ADD_PERSONNEL = 'ADD_PERSONNEL'
export const DELETE_PERSONNEL = 'DELETE_PERSONNEL'
//DemandeBillet 
export const GET_DEMANDEBILLETS = 'GET_DEMANDEBILLETS'
export const GET_DEMANDEBILLET = 'GET_DEMANDEBILLET'
export const EDIT_DEMANDEBILLET = 'EDIT_DEMANDEBILLET'
export const ADD_DEMANDEBILLET = 'ADD_DEMANDEBILLET'
export const DELETE_DEMANDEBILLET = 'DELETE_DEMANDEBILLET' 

//Piece Justificative 
export const GET_PIECEJUSTIFICATIVES = 'GET_PIECEJUSTIFICATIVES'
export const GET_PIECEJUSTIFICATIVE = 'GET_PIECEJUSTIFICATIVE'
export const EDIT_PIECEJUSTIFICATIVE = 'EDIT_PIECEJUSTIFICATIVE'
export const ADD_PIECEJUSTIFICATIVE = 'ADD_PIECEJUSTIFICATIVE'
export const DELETE_PIECEJUSTIFICATIVE = 'DELETE_PIECEJUSTIFICATIVE'

//TypeBillet 
export const GET_TYPEBILLETS = 'GET_TYPEBILLETS'
export const GET_TYPEBILLET = 'GET_TYPEBILLET'
export const EDIT_TYPEBILLET = 'EDIT_TYPEBILLET'
export const ADD_TYPEBILLET = 'ADD_TYPEBILLET'
export const DELETE_TYPEBILLET = 'DELETE_TYPEBILLET'



/*
    API CONNEXION
*/
export const URL = 'http://localhost:8080';

